# Generated by Django 5.2.1 on 2025-06-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashsale",
            options={
                "verbose_name": "Flash Sale",
                "verbose_name_plural": "Flash Sales",
            },
        ),
        migrations.AlterModelOptions(
            name="flashsaleitem",
            options={
                "verbose_name": "Flash Sale Item",
                "verbose_name_plural": "Flash Sale Items",
            },
        ),
        migrations.AddField(
            model_name="flashsale",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="flashsaleitem",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="flashsaleitem",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
