# Generated by Django 5.2.1 on 2025-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "promotions",
            "0002_alter_flashsale_options_alter_flashsaleitem_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("storage", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("reserved_stock", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="flash_deals/"),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flash Deal",
                "verbose_name_plural": "Flash Deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="flashsaleitem",
            name="flash_sale",
        ),
        migrations.AlterUniqueTogether(
            name="flashsaleitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="flashsaleitem",
            name="accessory",
        ),
        migrations.RemoveField(
            model_name="flashsaleitem",
            name="phone_variant",
        ),
        migrations.DeleteModel(
            name="FlashSale",
        ),
        migrations.DeleteModel(
            name="FlashSaleItem",
        ),
    ]
