# Generated by Django 5.2.1 on 2025-06-14 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0003_flashdeal_remove_flashsaleitem_flash_sale_and_more"),
    ]

    operations = []
