# Generated by Django 5.2.1 on 2025-06-14 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0004_auto_20250614_0018"),
    ]

    operations = []
