# Generated by Django 5.2.1 on 2025-06-14 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0004_create_flashdeal_table"),
        ("promotions", "0005_create_flashdeal_table"),
    ]

    operations = []
