# Generated by Django 5.2.1 on 2025-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessory",
            options={"verbose_name_plural": "Accessories"},
        ),
        migrations.AlterModelOptions(
            name="phone",
            options={"verbose_name_plural": "Phones"},
        ),
        migrations.AlterModelOptions(
            name="phonevariant",
            options={"verbose_name_plural": "Phone Variants"},
        ),
        migrations.AddField(
            model_name="accessory",
            name="is_best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accessory",
            name="is_new_arrival",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="phone",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="phone",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="color",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="phones/"),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="sku",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
