# Generated by Django 5.2.1 on 2025-07-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_accessory_options_alter_phone_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="is_best_seller",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="is_new_arrival",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="phone",
            name="brand",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="phone",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="is_best_seller",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="is_new_arrival",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="phonevariant",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, unique=True
            ),
        ),
    ]
